version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # endpoint principal
      - "4510-4559:4510-4559"  # portas internas para serviços
    environment:
      - SERVICES=sns,sqs,s3,rds
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data   # persistência local
      - LAMBDA_EXECUTOR=docker-reuse
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
